Develop almost production
Roman4ick/server-mesto pull request #4
Opened 2020-12-12 23:12 UTC by Roman4ick

2020-12-14 23:05 UTC, ramiltk53 requested changes
Здравствуйте!

Надо исправить:

- Укажите, пожалуйста, ip адрес и доменное имя сервера, на котором находится backend.
- Все ошибки должны быть централизовано, то есть не должно быть обработок ошибок типа res.send()
- Так же не работают все роуты кроме регистрации и логина, иногда возникает ошибка Cannot set headers after they are sent to the client, а в get user by id вообще пишет, что пользователя нет в бд и даёт ошибку 500. Необходимо это обрабатывать и возвращать 404. Пожалуйста, пройдитесь по всему функионалу , чтобы они были рабочие. 

В остальном проект хороший, нет лишних зависимостей в package.json, сохранена архитекрута приложения и функционал , реализована обработка ошибок и логгирование.

2020-12-23 17:13 UTC, ramiltk53 requested changes
Здравствуйте!

Спасибо за проделанную работу и изменения в коде. Хорошая работа на бекэнде. Но на фронте нет логина, нет регистрации. удалять можно любую карту и самое плохо это то что обращается ваш фронт нет к вашему API , а к `https://nomoreparties.co` . Поправьте, пожалуйста, этот момент. Обратитесь к наставнику, если вам нужна помощь

Желаю удачи! `:-)`

2020-12-25 08:14 UTC, ramiltk53 requested changes
Здравствуйте!
Работа хорошая, но надо посмотреть как это всё работает на сервере. Это обязательное условие. 

### Надо исправить:

- Добавьте публичный IP-адрес сервера и домен, по которому к нему можно обратиться, в файл README.md.

2020-12-25 09:19 UTC, Roman4ick commented
Добрый день, в README.md в ветке develop указана вся информацию, там есть и публичный IP  и доменные имена, если что-то не правильно делаю, то могу переписать.

2020-12-25 11:53 UTC, Roman4ick commented
Понял в чем ошибка, прошу прощения, затупил) исправил работу и отправил  на проверку.

2020-12-26 07:05 UTC, Roman4ick commented
> Здравствуйте!
> Работа хорошая, но надо посмотреть как это всё работает на сервере. Это обязательное условие. 
> 
> ### Надо исправить:
> 
> - Добавьте публичный IP-адрес сервера и домен, по которому к нему можно обратиться, в файл README.md.

Добрый день, внес изменения в работу.

2020-12-27 08:37 UTC, ramiltk53 approved these changes
Здравствуйте!

Спасибо за проделанную работу и изменения в коде!
Работа принята, но добавьте, пожалуйста, доменное имя сервера тоже, а не только айпи адрес

Желаю удачи на дипломной работе, в дальнейшем обучении и с Наступающим! `:-)`

2020-12-27 09:17 UTC, Roman4ick commented
> Здравствуйте!
> 
> Спасибо за проделанную работу и изменения в коде!
> Работа принята, но добавьте, пожалуйста, доменное имя сервера тоже, а не только айпи адрес
> 
> Желаю удачи на дипломной работе, в дальнейшем обучении и с Наступающим! `:-)`

Добрый день, спасибо большое, взаимно и вас с наступающим.

2020-12-27 19:58 UTC, merged